### ISSUE TITLE
离谱的数据库设置

### ISSUE THREAD

**Issue by nanshaws** [a1oyss/light_novel_backend#2]
兄弟说实话，你这样设置mysql就有点离谱了
![image](https://github.com/a1oyss/light_novel_backend/assets/98329722/57d035e2-0f51-427e-927d-f96724306626)
假如书本很多，那mysql的压力就有那么大了

**Comment by a1oyss** [comment]
> 兄弟说实话，你这样设置mysql就有点离谱了 ![image](https://private-user-images.githubusercontent.com/98329722/307223596-57d035e2-0f51-427e-927d-f96724306626.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NjY5NzYsIm5iZiI6MTcwODY2NjY3NiwicGF0aCI6Ii85ODMyOTcyMi8zMDcyMjM1OTYtNTdkMDM1ZTItMGY1MS00MjdlLTkyN2QtZjk2NzI0MzA2NjI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA1Mzc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3MTU5ZTNlM2ZiNzI3MzgzM2VkMGFjZDBjOTMyMzY3ZjkzOWQ0ZWQ4NmJkZGEyZTcxZWFlZGFlOWE4ZGJiNWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pgI-iNo5KEbl-YqckbojSUsOZRb0dam2Vh8d62410FU) 假如书本很多，那mysql的压力就有那么大了

这是我大学时写的作业，没考虑那么多
